spring:
  datasource:
    druid:
      username: ${MYSQL_USER:root}
      password: ${MYSQL_PWD:admin}
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${MYSQL_IP:localhost}:${MYSQL_PORT:3306}/${DB_NAME:geeklog}?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
logging:
  level:
    com.geeklog.mapper: debug

mybatis:
  configuration:
    aggressive-lazy-loading: false
    lazy-loading-enabled: true
  type-aliases-package: com.geeklog.domain
  mapper-locations: /mapper/**.xml

