spring:
  datasource:
    druid:
      username: ${MYSQL_USER:root}
      password: ${MYSQL_PWD:123456}
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${MYSQL_IP:localhost}:${MYSQL_PORT:3306}/${DB_NAME:geeklog}?useUnicode=true&characterEncoding=utf-8&useSSL=false
logging:
  level:
    com.geeklog.mapper: debug